### ISSUE TITLE
Chat bot not able to install

### ISSUE THREAD

**Issue by Mohanmk1** [ahmadfaizalbh/Chatbot#3]
HI,

While i am installing the chatbot i  am getting the below error.
![image](https://cloud.githubusercontent.com/assets/28388659/25703139/ed52a352-30f1-11e7-8ea1-e9241e20a977.png)

**Comment by ahmadfaizalbh** [comment]
Since you have problem with installing requests, please try installing it first by following docs below
[requests installation docs](http://docs.python-requests.org/en/master/user/install/)

you can install `requests` from [https://github.com/kennethreitz/requests/archive/v2.13.0.zip](https://github.com/kennethreitz/requests/archive/v2.13.0.zip) and then try installing [chatbot](https://github.com/ahmadfaizalbh/Chatbot)

It worked in windows 10 64bit version for me
![image](https://cloud.githubusercontent.com/assets/4068789/25704300/6b053c6c-30c8-11e7-946e-f7f7054ee59b.png)

**Comment by Mohanmk1** [comment]
Thanks it worked for me

**Comment by NaterciaMR** [comment]
thanks!! it worked for me too
